### ISSUE TITLE
Add NavBar component

### ISSUE THREAD

**Issue by Maurizio-F** [Maurizio-F/movie-night#3]
#### Description

The Navigation of the app.

#### Screenshots

![image](https://user-images.githubusercontent.com/68517390/121219736-4ee80980-c884-11eb-81c6-1be14b2faed5.png)

#### Tasks

- [x] Logo as png
- [x] Icons as svg´s
- [x] Build component as a div with the icons
- [x] Write story for storybook
